### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by DJBlackStore99** [xander1998/shield#1]
Hi , can you create a permission for example only cops can use this script to avoid other players to use!
Thank you for the script
keep up!

**Comment by chaixshot** [comment]
For developer, you can make it with you self.
vrp or esx?

**Comment by xander1998** [comment]
I am taking a break away from code. I can add a ped restriction but I will not be doing ESX or VRP because I do not like them

**Comment by DJBlackStore99** [comment]
@chaixshot Yes my understanding of coding is not that good to be able to create, I wish i could but still learning!
Yes i wanted for VRP!
@xander1998 yes you don't have to , thank you for sharing your work anyway with us!
Thank you!

**Comment by xander1998** [comment]
Will look into adding ped restriction after my break.
